//DO NOT EDIT THIS FILE, it is generated by idlcpp
//http://www.idlcpp.org

#pragma once

namespace pafcore{ class ClassType; }


namespace Resafety {
	namespace CyberUniverseStudio {
		class __declspec(dllexport) IFrameListener
		{
		public:
			static ::pafcore::ClassType* GetType();
			virtual ::pafcore::ClassType* getType();
			virtual size_t getAddress();

			virtual void frameMove(unsigned int interval) = 0 ;

		};

	}
}
