//DO NOT EDIT THIS FILE, it is generated by idlcpp
//http://www.idlcpp.org

#pragma once
//namespace EngineCore { class Node; }
//namespace EngineCore { class Scene; }
#include "NotifyHandler.h"
namespace EngineCore
{
	class __declspec(dllexport) NodeNotifyHandler : public PropertyChangedNotifyHandler
	{
	public:

		//virtual void onNodeAttachParent(Node* node,Node* parent);
		//virtual void onNodeDetachParent(Node* node,Node* parent);
		//virtual void onNodeEnterScene(Node* node,Scene* scene);
		//virtual void onNodeLeaveScene(Node* node,Scene* scene);
		//virtual void onNodeUpdateLocation(Node* node,bool direct);
		//virtual void onNodeComponentChangeTag(Node* node,Component* component);
	};
	
}
