//DO NOT EDIT THIS FILE, it is generated by idlcpp
//http://www.idlcpp.org

#pragma once
//#include "../Serializer/Reference.h"
//#include "../Serializer/Iterator.h"
#include <string>
namespace EngineCore { class Reference; };
namespace EngineCore { class Iterator; };
namespace EngineCore
{
	enum class PropertyChangedFlag
	{
		update,
		remove,
		add,
		reset,
		candidate_list
	};

	class __declspec(dllexport) NotifyHandler
	{
	public:
		virtual size_t getAddress();
	};

	class __declspec(dllexport) PropertyChangedNotifyHandler : public NotifyHandler
	{
	public:
		virtual size_t getAddress();

		virtual void onPropertyChanged(Reference* sender, std::string& propertyName, PropertyChangedFlag flag, Iterator* iterator);
		virtual void onPropertyAvailabilityChanged(Reference* sender, std::string& propertyName);
		virtual void onDynamicPropertyChanged(Reference* sender, std::string& propertyName, PropertyChangedFlag flag, Iterator* iterator);
		virtual void onUpdateDynamicProperty(Reference* sender);
	};


}