//DO NOT EDIT THIS FILE, it is generated by idlcpp
//http://www.idlcpp.org

#pragma once


namespace EngineCore { class GeoNode; }
namespace EngineCore { class GeoScene; }
namespace EngineCore { class Node; }


#include "../../EngineCore/Core/Engine/Node.h"
#include <string>

namespace EngineCore
{
		struct GeoNodeIterator
		{
		public:

			GeoNode* node;


			void moveNext();


			bool operator ==(const GeoNodeIterator& arg);

		};



		class __declspec(dllexport)	GeoNode : public Node
		{
		public:

			virtual size_t getAddress();

			std::string get_uuid() const;
			void set_uuid(std::string);




			GeoScene* getScene();


			GeoNode* getParent()const ;




			static GeoNode* New();

			friend class GeoLayer;
		public:
			GeoNode();
			~GeoNode();
		public:
			std::string m_uuid;
			std::string m_releaseMemoryUuid;

			//RTTR_ENABLE(Node)

		};


		inline bool GeoNodeIterator::operator == (const GeoNodeIterator& arg)
		{
			return node == arg.node;
		}
		
		inline GeoNode* GeoNode::getParent() const
		{
			return static_cast<GeoNode*>(m_parent);
		}

		inline std::string GeoNode::get_uuid() const
		{
			return m_uuid.c_str();
		}

		inline void GeoNode::set_uuid(std::string uuid)
		{
			//GeoNodeManager::GetInstance()->removeGeoNode(m_uuid);
			m_uuid = uuid.c_str();
			//GeoNodeManager::GetInstance()->addGeoNode(m_uuid, this);
		}


	


}