//DO NOT EDIT THIS FILE, it is generated by idlcpp
//http://www.idlcpp.org

#pragma once

#include "../../EngineCore/Core/Engine/Scene.h"
#include "./GeoNode.h"




namespace EngineCore
{

		class __declspec(dllexport) GeoScene : public Scene
		{
		public:
			virtual size_t getAddress();
			static GeoScene* New();
		protected:
			GeoScene();
			~GeoScene();
		//public:
		//	GeoNode* getFirstTopNode() const;
		//	GeoNode* getLastTopNode() const;

		};

	
}